version: '3'
services:
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "1234567"
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1434"

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
